### ISSUE TITLE
友链选项卡中，ReturnZeroGirl的小站地址（域名）错误

### ISSUE THREAD

**Issue by ReturnZeroGirl** [FTS427/FTS427.github.io#22]
我的网站的域名从returnzerogirl.top改成returnzerogirl.com了，请及时更正

**Comment by FTS427** [comment]
Fixed in [dea02ff](https://github.com/FTS427/FTS427.github.io/commit/dea02ff9c7eba41c0daaa5bab362fbe429dfbe22)
